# Generated by Django 3.1.4 on 2020-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201209_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('online', 'On-line'), ('offline', 'off-line')], max_length=15, null=True),
        ),
    ]
