# Generated by Django 3.1.4 on 2020-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201209_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
